using System.Runtime.InteropServices;
using Avalonia;
using Avalonia.Media.Imaging;
using ReProgman.Win31;
using ReProgman.Model;

namespace ReProgman.IconExport;

/// <summary>
/// Writes the hand-drawn group icon as the icon assets of the application:
/// a Windows .ico and a macOS .icns. Both are committed to the repository and
/// regenerated by this tool (see build/export-icons.ps1), so the icon on the
/// executable can never drift from the icon drawn inside the app, and no build
/// machine has to render anything.
/// </summary>
internal static class IconAssets
{
    // The slots of an icon suite, as (chunk type, pixel size). This is the set
    // iconutil produces from a full .iconset: the plain sizes plus their @2x
    // companions, which is why 32, 256 and 512 each appear under two types.
    private static readonly (string Type, int Size)[] IcnsEntries =
    [
        ("icp4", 16),
        ("ic11", 32),
        ("icp5", 32),
        ("ic12", 64),
        ("ic07", 128),
        ("ic13", 256),
        ("ic08", 256),
        ("ic14", 512),
        ("ic09", 512),
        ("ic10", 1024),
    ];

    // The sizes Explorer picks from: list view, details, tiles, and the extra
    // large view that also feeds the thumbnails.
    private static readonly int[] IcoSizes = [16, 32, 48, 256];

    /// <summary>
    /// Writes the icon of the macOS bundle. Like the .ico this is committed and
    /// only regenerated when the artwork changes, so the publish script simply
    /// copies it and a build machine needs neither a window server nor iconutil.
    /// </summary>
    public static void WriteIcns(string path)
    {
        var images = new List<IcnsPngImage>();
        foreach (var group in IcnsEntries.GroupBy(e => e.Size))
        {
            using var bitmap = GroupIconArt.RenderToBitmap(group.Key);
            using var stream = new MemoryStream();
            bitmap.Save(stream);
            var png = stream.ToArray();
            images.AddRange(group.Select(entry => new IcnsPngImage(entry.Type, png)));
        }

        File.WriteAllBytes(path, IcnsWriter.Build(images));
    }

    /// <summary>
    /// Writes the icon of the Windows executable. The result is committed to the
    /// repository because <c>ApplicationIcon</c> has to exist before the build
    /// that would produce it; re-run this whenever the drawing changes.
    /// </summary>
    public static void WriteIco(string path)
    {
        var images = new List<IcoImage>();
        foreach (var size in IcoSizes)
        {
            using var bitmap = GroupIconArt.RenderToBitmap(size);
            if (size == 256)
            {
                // The largest entry is stored as PNG, as is customary, which keeps
                // the file small enough to sit comfortably in the executable.
                using var stream = new MemoryStream();
                bitmap.Save(stream);
                images.Add(IcoImage.FromPng(size, stream.ToArray()));
            }
            else
            {
                images.Add(IcoImage.FromBgra(size, CopyBgra(bitmap, size)));
            }
        }

        File.WriteAllBytes(path, IcoWriter.Build(images));
    }

    private static byte[] CopyBgra(RenderTargetBitmap bitmap, int size)
    {
        var stride = size * 4;
        var pixels = new byte[stride * size];
        var handle = GCHandle.Alloc(pixels, GCHandleType.Pinned);
        try
        {
            bitmap.CopyPixels(new PixelRect(0, 0, size, size), handle.AddrOfPinnedObject(), pixels.Length, stride);
        }
        finally
        {
            handle.Free();
        }

        return pixels;
    }
}
